version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api
    container_name: api
    volumes:
      - ./api:/work/api
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: front
    container_name: front
    volumes:
      - ./front:/work/front
    ports:
      - 8080:8080
    tty: true

  db:
    image: postgres:13-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
